### ISSUE TITLE
Define transitions for Master FSM

### ISSUE THREAD

**Issue by MrZebulon** [EPFLRocketTeam/2024_I_AV_SW_ARCH#7]
Teensy is the Master --> work in BaseTeensyBoardClass
Also raise/lower flags in SystemClass
**Assigned person shall work on a different branch named dev/<name>**

**Comment by phamelink** [comment]
<img width="1292" alt="Screenshot 2024-03-10 at 19 30 16" src="https://github.com/EPFLRocketTeam/2024_I_AV_SW_ARCH/assets/75215820/9624a2ee-b1f9-4ba4-8dc0-90344def1375">
Hey @MrZebulon,

I get this error from my IDE, I'm on CLION. Do you know how to fix this and why this happens ? I know more or less what I can do still with the sys, but I'd rather not code blind 🙈

**Comment by MrZebulon** [comment]
Odd, it does seem to find it in BaseBoardClass. Might be CLion going dumb. You could try the following:
- building the target
- clearing the cmake cache
- reloading the cmake file
- check that the imports are clean

Also, is this the only instance of the problem ?

**Comment by phamelink** [comment]
Thanks I'll try that out!
